### ISSUE TITLE
Building with AoT throws errors

### ISSUE THREAD

**Issue by leolorenzoluis** [mseemann/angular2-mdl#516] opened 2017-02-07 04:02 UTC
Using latest version for compiler and mdl

```
 ngc -p ./tsconfig-aot.json

Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-dialog.component.ngfactory.ts:153:18: Property 'template' is private and only accessible within class 'MdlDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:261:46: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:261:104: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:266:59: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:266:117: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:269:46: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:269:104: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:274:43: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:274:101: Property 'dialogConfiguration' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/dialog/mdl-simple-dialog.component.ngfactory.ts:283:20: Property 'buttons' is private and only accessible within class 'MdlSimpleDialogComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/snackbar/mdl-snackbar.service.ngfactory.ts:237:57: Property 'showIt' is private and only accessible within class 'MdlSnackbarComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout.component.ngfactory.ts:170:42: Property 'header' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout.component.ngfactory.ts:172:42: Property 'drawer' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout.component.ngfactory.ts:174:42: Property 'content' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout.component.ngfactory.ts:368:45: Property 'drawer' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:59:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:102:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:145:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:188:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:231:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:274:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:317:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/common/mdl-ripple.directive.ngfactory.ts:361:9: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout-header.component.ngfactory.ts:97:48: Property 'onTransitionEnd' is protected and only accessible within class 'MdlLayoutHeaderComponent' and its subclasses.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/layout/mdl-layout-header.component.ngfactory.ts:101:48: Property 'onClick' is protected and only accessible within class 'MdlLayoutHeaderComponent' and its subclasses.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/home/home.component.ngfactory.ts:231:42: Property 'header' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/home/home.component.ngfactory.ts:233:42: Property 'drawer' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/home/home.component.ngfactory.ts:235:42: Property 'content' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/button/mdl-button.component.ngfactory.ts:101:7: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/textfield/mdl-textfield.component.ngfactory.ts:355:9: Supplied parameters do not match any signature of call target.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/node_modules/angular2-mdl/components/textfield/mdl-textfield.component.ngfactory.ts:1239:20: Property 'inputEl' is private and only accessible within class 'MdlTextFieldComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/register/register.component.ngfactory.ts:271:42: Property 'header' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/register/register.component.ngfactory.ts:273:42: Property 'drawer' is private and only accessible within class 'MdlLayoutComponent'.
Error at C:/Users/w00t/Source/Repos/Test/src/Test.WebApplication/aot/client/app/register/register.component.ngfactory.ts:275:42: Property 'content' is private and only accessible within class 'MdlLayoutComponent'.
```

**Comment by mseemann** [comment] 2017-02-07 08:23
aot works for me. see https://github.com/mseemann/a2-mdl-webpack

**Comment by jlee1201** [comment] 2017-02-07 18:33
While I confirmed that your angular-cli based starter works with AoT, it is not working for me using https://github.com/AngularClass/angular2-webpack-starter -- I get same errors around property scope as @leolorenzoluis .   angular2-mdl is the only package out of 15+ that we are using that does not work with the angular2-webpack-starter repo :(

**Comment by mseemann** [comment] 2017-02-07 22:51
@jlee1201 this project is open to pr. if you think there is something that can be improved provide a pr! on the other side - there is no one who told you you have to use this package!

**Comment by jlee1201** [comment] 2017-02-09 01:10
no offense intended.  I was responding to your "aot works for me" comment.  I went ahead and made fixes and submitted PR

**Comment by leolorenzoluis** [comment] 2017-02-09 03:54
FYI

**Comment by mseemann** [comment] 2017-02-12 12:32
closed by: https://github.com/mseemann/angular2-mdl/pull/528

**Closed by mseemann** 2017-02-12 12:32 UTC
